<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

numpy.ndarray

array(['1', '2', '3', '4'], dtype='<U1')

dtype('<U1')

## Create an array of 10 zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of the integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

[1 3 5 7 9]


## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

[ 6  9 10]


## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [ ]:
A = np.random.random((5,3))
B = np.random.random((3,2))


[[1.44576481 1.53425016]
 [1.09322182 0.67844804]
 [0.91008796 1.21252048]
 [0.89292414 0.60539749]
 [0.57727794 0.93558888]]


# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises

 **Context:** You are a Data Analyst at "TechCorp". 
HR has asked you to analyze employee data to understand attrition, salary trends, and job satisfaction.

**Instructions:**
1. Write your code in the empty cells.

### 1. Load & Inspect
Load `employee_data.csv` into a DataFrame named `df`. Display the first 5 rows and check column data types.

EmployeeID  Age              Department            JobRole Attrition  \
195        1196   40  Research & Development         Sales Exec       Yes   
196        1197   41                   Sales     Lab Technician        No   
197        1198   53  Research & Development     Data Scientist        No   
198        1199   28                   Sales  Software Engineer        No   
199        1200   54  Research & Development         Sales Exec       Yes   

     MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
195           9704               7                4                  3   
196           7422              17                3                  3   
197          12984               7                3                  3   
198           4759              14                4                  3   
199          14404              15                1                  3   

     PercentSalaryHike  DistanceFromHome MaritalStatus  
195                 10                29       Married  
196                 12                15      Divorced  
197                 23                28      Divorced  
198                 21                 3       Married  
199                 19                 8        Single

### 2. Filter IT Department
Create a DataFrame `df_rd` containing only employees from the `'Research & Development'` department.

EmployeeID  Age              Department         JobRole Attrition  \
0        1001   50  Research & Development  Data Scientist        No   
1        1002   36  Research & Development  Data Scientist        No   
5        1006   44  Research & Development      HR Manager       Yes   
6        1007   32  Research & Development  Data Scientist        No   
8        1009   45  Research & Development  Data Scientist        No   

   MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0           8415              19                1                  4   
1           6391              19                3                  4   
5           8468               8                4                  3   
6          11007              19                2                  3   
8          12444               1                3                  3   

   PercentSalaryHike  DistanceFromHome MaritalStatus  
0                 16                20       Married  
1                 21                21       Married  
5                 12                11        Single  
6                 19                 2       Married  
8                 16                18       Married

### 3. Salary Check
Find the employee with the highest `MonthlyIncome`. Display their `JobRole` and `MonthlyIncome`.

JobRole          HR Manager
MonthlyIncome         14954
Name: 28, dtype: object

### 4. Missing Values
Check if there are any missing values (`NaN`) in the dataset.

EmployeeID           0
Age                  0
Department           0
JobRole              0
Attrition            0
MonthlyIncome        0
YearsAtCompany       0
JobSatisfaction      0
PerformanceRating    0
PercentSalaryHike    0
DistanceFromHome     0
MaritalStatus        0
dtype: int64


### 5. Average Age by Role
Calculate the average `Age` for each `JobRole`.

JobRole
Data Scientist       38.771429
HR Manager           39.926829
Lab Technician       38.673469
Sales Exec           44.000000
Software Engineer    40.395349
Name: Age, dtype: float64

### 6. Attrition Count
How many employees have left the company? (Count values in the `Attrition` column).

Attrition
No     167
Yes     33
Name: count, dtype: int64


### 7. High Performers
Filter for employees with `PercentSalaryHike` > 15 **AND** `PerformanceRating` == 4.

EmployeeID  Age              Department            JobRole Attrition  \
0          1001   50  Research & Development     Data Scientist        No   
1          1002   36  Research & Development     Data Scientist        No   
2          1003   29                   Sales     Data Scientist        No   
3          1004   42                   Sales         Sales Exec        No   
16         1017   59                   Sales  Software Engineer       Yes   
25         1026   37         Human Resources     Data Scientist        No   
29         1030   28  Research & Development  Software Engineer        No   
37         1038   47  Research & Development  Software Engineer        No   
40         1041   49  Research & Development         Sales Exec       Yes   
45         1046   38  Research & Development  Software Engineer        No   
46         1047   57  Research & Development         Sales Exec        No   
51         1052   50  Research & Development         Sales Exec        No   
60         1061   29  Research & Development     Lab Technician        No   
75         1076   45  Research & Development         HR Manager        No   
77         1078   29  Research & Development     Data Scientist        No   
103        1104   35  Research & Development     Lab Technician        No   
108        1109   35                   Sales         Sales Exec        No   
110        1111   30  Research & Development     Lab Technician        No   
118        1119   51  Research & Development  Software Engineer        No   
120        1121   44  Research & Development         Sales Exec        No   
128        1129   49  Research & Development     Lab Technician        No   
151        1152   53                   Sales         Sales Exec        No   
157        1158   58  Research & Development     Data Scientist        No   
174        1175   32  Research & Development         HR Manager        No   
181        1182   43                   Sales     Data Scientist       Yes   
185        1186   30  Research & Development     Data Scientist        No   
187        1188   37                   Sales     Data Scientist        No   

     MonthlyIncome  YearsAtCompany  JobSatisfaction  PerformanceRating  \
0             8415              19                1                  4   
1             6391              19                3                  4   
2            14157              17                1                  4   
3            14835              13                3                  4   
16           10577               6                2                  4   
25           12510              19                4                  4   
29           10804              18                3                  4   
37            5192               3                3                  4   
40            7033              15                1                  4   
45           14302              14                1                  4   
46            4970              11                2                  4   
51           11135              16                4                  4   
60            3922               4                3                  4   
75           14045               2                2                  4   
77           10326               3                4                  4   
103          13541               4                1                  4   
108          10783               5                2                  4   
110          14473              12                1                  4   
118           7451              10                2                  4   
120           6876              17                1                  4   
128           8109              11                2                  4   
151          14694               9                1                  4   
157           7212               8                4                  4   
174           4205              17                2                  4  

### 8. Satisfaction Analysis (Pivot Table)
Create a pivot table showing the **average** `MonthlyIncome` for each `Department` (rows) broken down by `JobSatisfaction` (columns).

JobSatisfaction                    1            2            3            4
Department                                                                 
Human Resources          8494.666667  8822.200000  8196.333333  7744.833333
Research & Development  10810.718750  8581.125000  8648.090909  8930.304348
Sales                    9795.789474  9590.461538  8459.461538  9045.000000

### 9. Feature Engineering (Seniority)
Create a new column `Seniority`.
* If `YearsAtCompany` > 10, value is `'Senior'`
* Otherwise, value is `'Junior'`

Count how many Seniors vs Juniors there are.

Seniority
Junior    104
Senior     96
Name: count, dtype: int64


### 10. Retention Risk (Complex Filter)
Identify 'High Risk' employees who meet **ALL** these criteria:
1. `MaritalStatus` is 'Single'
2. `JobSatisfaction` is less than 3
3. `DistanceFromHome` > 10

Display their `EmployeeID` and `JobRole`.

EmployeeID            JobRole
20         1021  Software Engineer
30         1031     Lab Technician
42         1043         HR Manager
43         1044         HR Manager
45         1046  Software Engineer
78         1079     Data Scientist
93         1094     Lab Technician
108        1109         Sales Exec
112        1113     Data Scientist
119        1120  Software Engineer
124        1125         HR Manager
159        1160         HR Manager
161        1162     Data Scientist
168        1169         HR Manager
169        1170         Sales Exec
172        1173  Software Engineer
174        1175         HR Manager
183        1184     Lab Technician
185        1186     Data Scientist